/* 
 * Aapplication generated by the wordlist based on the victim’s data.
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 */


// Header
#include<stdio.h>
#include<string.h>


// Functions declaration
char Menu();




// main
int main(){
    int choise = Menu();
    printf("\n\t ---> choise : %d", choise);




    
    return 0;
}


// Functions definition 











char Menu(){
    char input[50];
    int choise = 0;


    while(1)
    {
    printf("\n\n\t===============================================\n\t"

                    "\tMenu d\'application\n\t"

            "===============================================\n\t"

            "[1] afficher les donnees\n\t"

            "[2] ajouter une donnee\n\t"

            "[3] rechercher sur une donnee\n\t"

            "[4] supprimer une donnee\n\t"

            "[5] supprimer les donnees repetes\n\t"

            "[6] genere le wordlist\n\t"

            "[7] genere le wordlist dans un fichier .txt \n\t"

            "[8] afficher les donnees de type entier\n\t"

            "===============================================\n\t"

            "\n\tTapez votre choix [1-6] : ");

        fgets(input, sizeof(input), stdin);

        if( (sscanf(input, "%d", &choise) != 1) || (choise < 1 || choise > 6)) 
            printf("\n\t-- Saisie Invalide !! --\n"); 
        else
            break;
    };
    
    return choise;
}
